name: shelf_server
description: A work-in-progress backend server using shelf
version: 0.0.1
homepage: https://github.com/mcmahonjohn/shelf_server

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  test: <2.0.0
